# snakemake -j 8 --use-conda
## Config file for setting options

db: "resources/database"
input: "input/metafile.txt"

## Number of cores
ncores: 8

impute: true #activate imputation step with impute2 tool

############################################
## ADDITIONAL parameters
############################################

## Genome reference
ref:
## genome build 
  build: hg19 # hg38/hg19

database_url:
  GRCh38:
    ClinVar: "https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz"
    Cosmic: "http://ftp.ensembl.org/pub/current_variation/vcf/homo_sapiens/homo_sapiens_somatic.vcf.gz"
    reference_data: "" # needs to be added
  GRCh37:
    ClinVar: "https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/clinvar.vcf.gz"
    Cosmic: "http://ftp.ensembl.org/pub/grch37/current/variation/vcf/homo_sapiens/homo_sapiens_somatic.vcf.gz"
    reference_data: "https://mathgen.stats.ox.ac.uk/impute/ALL_1000G_phase1integrated_v3_impute.tgz"
    

