# snakemake -j 1 --use-conda
## Config file for setting options


############################################
## ADDITIONAL parameters
############################################

## Number of cores
ncores: 8

## Genome reference
ref:
## ensembl release
  release: 109  # The most recent release of human genome is 104 (May 2023)
## genome build 
  build: hg19 # hg38/hg19

database_url:
  GRCh38:
    ClinVar: "https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz"
    Cosmic: "http://ftp.ensembl.org/pub/current_variation/vcf/homo_sapiens/homo_sapiens_somatic.vcf.gz"
    reference_data: ""
  GRCh37:
    ClinVar: "https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/clinvar.vcf.gz"
    Cosmic: "http://ftp.ensembl.org/pub/grch37/current/variation/vcf/homo_sapiens/homo_sapiens_somatic.vcf.gz"
    reference_data: "https://mathgen.stats.ox.ac.uk/impute/ALL_1000G_phase1integrated_v3_impute.tgz"
    
db: "database"
input: "input/metafile.txt"
